const TABLE_HEAD = ["Name", "Department", "Shift", "Club Id"];

const TABLE_ROWS = [
    { name: "AARTHI S ", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC001' },
    { name: "Aravind S", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC002' },
    { name: "Balaguru K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC003' },
    { name: "BARATHVIKRAMAN S K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC004' },
    { name: "Bhagavatula Nagasai Manogna", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC005' },
    { name: "Dhanushya", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC006' },
    { name: "Gayathri J", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC007' },
    { name: "Harivenkat R ", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC008' },
    { name: "KATHIRRAM S", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC009' },
    { name: "Naveen raj Y", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC010' },
    { name: "NITHYA SRI C B", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC011' },
    { name: "SANGEETHA. M", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC012' },
    { name: "Sanjay Kumar K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC013' },
    { name: "Venkatesh B", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC014' },
    { name: "Abdul Azees H", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC015' },
    { name: "Amrutha", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC016' },
    { name: "Dharshan MP", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC017' },
    { name: "Dharshith R", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC018' },
    { name: "Fathima Masooma", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC019' },
    { name: "Lokesh G", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC020' },
    { name: "MOHAMED SALMAN A", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC021' },
    { name: "Nabeel G", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC022' },
    { name: "Naveen Raj .J", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC023' },
    { name: "Parthiban S", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC024' },
    { name: "RAJADURAI K", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC025' },
    { name: "Rinoy Dennis", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC026' },
    { name: "Sakthivel R", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC027' },
    { name: "SIBICHAN K", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC028' },
    { name: "Swathy R", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC029' },
    { name: "VIKRAM S", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC030' },
    { name: "Yashwanth P", department: "BSc IT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC031' },
    { name: "Monisha.R", department: "BSc CT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC032' },
    { name: "Anushya", department: "BSc CT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC033' },
    { name: "Kaveri.J", department: "BSc CT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC034' },
    { name: "Padmapriya.G", department: "BSc CT", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC035' },
    { name: "Praveen Kumar M ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC036' },
    { name: "Mohankumar.D ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC037' },
    { name: "A SHARAN SUBBU ", department: "BSc CS CS", year: "NAN", shift: "Shift 2", clubId: 'SRC22PC038' },
    { name: "Karthic Roshan", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC22PC039' },
    { name: "Koushik", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC22PC040' },
    { name: "Sahana.L", department: "BCA", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC041' },
    { name: "SHWETHA M", department: "BCA", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC042' },
    { name: "Abhi Pal V", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC043' },
    { name: "AKASH.S", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC044' },
    { name: "Dharanidharan", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC045' },
    { name: "j.sijoy", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC046' },
    { name: "Jishnu S", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC047' },
    { name: "M.Thejeshwar", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC048' },
    { name: "Mohammed irfaan.U", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC049' },
    { name: "R Naveen Raj", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC050' },
    { name: "Saravanan", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC051' },
    { name: "Saravaneeshwaran", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC052' },
    { name: "Sriram.R", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC053' },

    // 2nd year 
    { name: "Gayathri", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC001' },
    { name: "Saravanan.V", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC002' },
    { name: "Thiruvikram", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC003' },
    { name: "Vishal S", department: "BSc CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC004' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC005' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC006' },
    { name: "G.DHARSHINI", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC007' },
    { name: "Ghayathri.M", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC008' },
    { name: "Jeyadharshini s", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC009' },
    { name: "Kavipriya J", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC010' },
    { name: "Selvi.R", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC011' },
    { name: "Shalini v", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC012' },
    { name: "MONISHA S", department: "BSc IT", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC013' },
    { name: "Nandita", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC014' },
    { name: "Sakthi priyalakshmi .R", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC015' },
    { name: "SANTHIYA.K", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC016' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC017' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC018' },
    { name: "Logeshwaran.v", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC019' },
    { name: "Muthukumar. M", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC020' },
    { name: "N.DHAYANANDH", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC021' },
    { name: "POORNILA I P", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC022' },
    { name: "Sarath P", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC023' },
    { name: "VIKAAS K S", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC024' },
    { name: "Megha", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC025' },
    { name: "Pranavan", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC026' },
    { name: "Sanjai pandi . P", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC027' },
    { name: "Sheba Samuel", department: "BSc CS DA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC028' },
    { name: "Sree Harni", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC029' },
    { name: "Velan J", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC030' },
    { name: "Deenadhayal.P.S", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC031' },
    { name: "Immanuel jayaruban P", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC032' },
    { name: "K. K. Hariharan", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC033' },
    { name: "Nandha SriHari", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC034' },
    { name: "sai prakash B", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC035' },
    { name: "Sohil Vasan.G.S", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC036' },
    { name: "Surya Prakash", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC037' },
    { name: "Aarthi", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC038' },
    { name: "Daksa", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC039' },
    { name: "Gautham G", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC040' },
    { name: "Madhusudan v", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC041' },
    { name: "Mathivathani", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC042' },
    { name: "Raghul shreeram S", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC043' },
    { name: "Sivanantham V", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC044' },
    { name: "Divyesh R", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC045' },
    { name: "MANJUNATH BAIRAV M", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC046' },
    { name: "Manoj P", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC047' },
    { name: "Srikanth R G", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC048' },
    { name: "Srinath.R", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC049' },
    { name: "Thiyaasree K.C", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC050' },
    { name: "Dharani.S", department: "BSC.COMPUTER SCIENCE WITH CYBER SECURITY", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC051' },
    { name: "Aswitha. M", department: "BSC CS with Cyber Security", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC052' },
    { name: "Arshaad Basel", department: "BSC CS with Cyber Security", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC053' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC054' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC055' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC056' },
    { name: "Arun Kumar", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC057' },
    { name: "Hari prasath", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC058' },
    { name: "Harish.A", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC059' },
    { name: "Meeth.R", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC060' },
    { name: "Sanjay. J", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC061' },
    { name: "NAN", department: "NAN", year: "NAN", shift: "NAN", clubId: 'SRC23PC062' }
];

export { TABLE_HEAD, TABLE_ROWS };
