const TABLE_HEAD = ["Name", "Department", "Shift", "Club Id"];

const TABLE_ROWS = [
    { name: "AARTHI S ", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC001' },
    { name: "Aravind S", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC002' },
    { name: "Balaguru K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC003' },
    { name: "BARATHVIKRAMAN S K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC004' },
    { name: "Bhagavatula Nagasai Manogna", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC005' },
    { name: "Dhanushya", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC006' },
    { name: "Gayathri J", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC007' },
    { name: "Harivenkat R ", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC008' },
    { name: "KATHIRRAM S", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC009' },
    { name: "Naveen raj Y", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC010' },
    { name: "NITHYA SRI C B", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC011' },
    { name: "SANGEETHA. M", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC012' },
    { name: "Sanjay Kumar K", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC013' },
    { name: "Venkatesh B", department: "BSc CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC014' },
    { name: "Abdul Azees H", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC015' },
    { name: "Amrutha", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC016' },
    { name: "Dharshan MP", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC017' },
    { name: "Elancherraiyan S", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC018' },
    { name: "HARISUDHAN ", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC019' },
    { name: "MAHENDRAN.S", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC020' },
    { name: "MANI KANDAN M ", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC021' },
    { name: "Nishanth", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC022' },
    { name: "Pranesh A", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC023' },
    { name: "Sarath Kumar R", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC024' },
    { name: "Shabi", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC025' },
    { name: "SHANMUGAM.A", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC026' },
    { name: "Vijay Anand P", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC027' },
    { name: "Vijayakanth ", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC028' },
    { name: "Vinay S", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC029' },
    { name: "Yamini K", department: "BSc IT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC030' },
    { name: "Hari Krishna ", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC031' },
    { name: "Kannan M", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC032' },
    { name: "Naveen", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC033' },
    { name: "Karthik M", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC034' },
    { name: "Prasanth N", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC035' },
    { name: "Nithiya P", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC036' },
    { name: "HARINI V", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC037' },
    { name: "DIVYA V ", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC038' },
    { name: "Hakeem Ashraf ", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC039' },
    { name: "Jegadeesh A", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC040' },
    { name: "TAMILVANAN A", department: "BSc CT", year: "III - Year", shift: "Shift1", clubId: 'SRC22PC041' },
    { name: "Akshay", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC042' },
    { name: "Arvind A ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC043' },
    { name: "Siddharth M ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC044' },
    { name: "SURYA N ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC045' },
    { name: "Dhinesh kumar R", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC046' },
    { name: "Mohamed Riyazudeen", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC047' },
    { name: "Anish R", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC048' },
    { name: "NAVEEN KUMAR A", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC049' },
    { name: "Mohankumar.D ", department: "BSc CS CS", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC050' },
    { name: "A SHARAN SUBBU ", department: "BSc CS CS", year: "NaN", shift: "Shift 2", clubId: 'SRC22PC051' },
    { name: "Karthic Roshan", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC22PC052' },
    { name: "Koushik", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC22PC053' },
    { name: "Sahana.L", department: "BCA", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC054' },
    { name: "SHWETHA M", department: "BCA", year: "III - Year", shift: "Shift 1", clubId: 'SRC22PC055' },
    { name: "Abhi Pal V", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC056' },
    { name: "AKASH.S", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC057' },
    { name: "Dharanidharan", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC058' },
    { name: "j.sijoy", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC059' },
    { name: "Jishnu S", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC060' },
    { name: "M.Thejeshwar", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC061' },
    { name: "Mohammed irfaan.U", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC062' },
    { name: "R Naveen Raj", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC063' },
    { name: "Saravanan", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC064' },
    { name: "Saravaneeshwaran", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC065' },
    { name: "Sriram.R", department: "BCA", year: "III - Year", shift: "Shift 2", clubId: 'SRC22PC066' },


    //2nd year 
    { name: "Gayathri", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC001' },
    { name: "Saravanan.V", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC002' },
    { name: "Thiruvikram", department: "BSc CS", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC003' },
    { name: "Vishal S", department: "BSc CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC004' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC005' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC006' },
    { name: "G.DHARSHINI", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC007' },
    { name: "Ghayathri.M", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC008' },
    { name: "Jeyadharshini s", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC009' },
    { name: "Kavipriya J", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC010' },
    { name: "Selvi.R", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC011' },
    { name: "Shalini v", department: "BSc CS", year: "II - Year", shift: "Shift2", clubId: 'SRC23PC012' },
    { name: "MONISHA S", department: "BSc IT", year: "II - Year", shift: "Shift1", clubId: 'SRC23PC013' },
    { name: "Nandita", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC014' },
    { name: "Sakthi priyalakshmi .R", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC015' },
    { name: "SANTHIYA.K", department: "BSc IT", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC016' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC017' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC018' },
    { name: "Logeshwaran.v", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC019' },
    { name: "Muthukumar. M", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC020' },
    { name: "N.DHAYANANDH", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC021' },
    { name: "POORNILA I P", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC022' },
    { name: "Sarath P", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC023' },
    { name: "VIKAAS K S", department: "BSc IT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC024' },
    { name: "Megha", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC025' },
    { name: "Pranavan", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC026' },
    { name: "Sanjai pandi . P", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC027' },
    { name: "Sheba Samuel", department: "BSc CS DA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC028' },
    { name: "Sree Harni", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC029' },
    { name: "Velan J", department: "Bsc CSDA", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC030' },
    { name: "Deenadhayal.P.S", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC031' },
    { name: "Immanuel jayaruban P", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC032' },
    { name: "K. K. Hariharan", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC033' },
    { name: "Nandha SriHari", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC034' },
    { name: "sai prakash B", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC035' },
    { name: "Sohil Vasan.G.S", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC036' },
    { name: "Surya Prakash", department: "BSc AI DS", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC037' },
    { name: "Aarthi", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC038' },
    { name: "Daksa", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC039' },
    { name: "Gautham G", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC040' },
    { name: "Madhusudan v", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC041' },
    { name: "Raghul shreeram S", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC042' },
    { name: "Sivanantham V", department: "BSc CT", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC043' },
    { name: "Divyesh R", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC044' },
    { name: "MANJUNATH BAIRAV M", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC045' },
    { name: "Manoj P", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC046' },
    { name: "Srikanth R G", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC047' },
    { name: "Srinath.R", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC048' },
    { name: "Thiyaasree K.C", department: "BSc CS CS", year: "II - Year", shift: "Shift 1", clubId: 'SRC23PC049' },
    { name: "Dharani.S", department: "BSC.COMPUTER SCIENCE WITH CYBER SECURITY", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC050' },
    { name: "Aswitha. M", department: "BSC CS with Cyber Security", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC051' },
    { name: "Arshaad Basel", department: "BSC CS with Cyber Security", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC052' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC053' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC054' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC055' },
    { name: "Arun Kumar", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC056' },
    { name: "Hari prasath", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC057' },
    { name: "Harish.A", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC058' },
    { name: "Meeth.R", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC059' },
    { name: "Sanjay. J", department: "BCA", year: "II - Year", shift: "Shift 2", clubId: 'SRC23PC060' },
    { name: "NaN", department: "NaN", year: "NaN", shift: "NaN", clubId: 'SRC23PC061' },


    //1st year 
    { name: "Brindha.S", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC001' },
    { name: "HAAJIRAA.B.H", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC002' },
    { name: "Kewin Immanual", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC003' },
    { name: "Sanjiv Krishnaa", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC004' },
    { name: "Tharrun S", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC005' },
    { name: "Yukana", department: "BSC CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC006' },
    { name: "Udhaya Sankar", department: "BSC CS", year: "1", shift: "Shift 2", clubId: 'SRC24PC007' },
    { name: "Yamuna dharshini", department: "BSC CS", year: "1", shift: "Shift 2", clubId: 'SRC24PC008' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC009' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC010' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC011' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC012' },
    { name: "Deepak kumar.m.v", department: "BSC IT", year: "1", shift: "Shift 1", clubId: 'SRC24PC013' },
    { name: "Kirubakaran", department: "BSC IT", year: "1", shift: "Shift 1", clubId: 'SRC24PC014' },
    { name: "Pravin raj", department: "BSC IT", year: "1", shift: "Shift 1", clubId: 'SRC24PC015' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC016' },
    { name: "Choudhry", department: "BSC IT", year: "1", shift: "Shift 2", clubId: 'SRC24PC017' },
    { name: "rakshana.S", department: "BSC IT", year: "1", shift: "Shift 2", clubId: 'SRC24PC018' },
    { name: "sakthisowndhariya.S", department: "BSC IT", year: "1", shift: "Shift 2", clubId: 'SRC24PC019' },
    { name: "Vinothkannan.S", department: "BSC IT", year: "1", shift: "Shift 2", clubId: 'SRC24PC020' },
    { name: "visrutha.M", department: "BSC IT", year: "1", shift: "Shift 2", clubId: 'SRC24PC021' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC022' },
    { name: "KAVINRAJ J S", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC023' },
    { name: "Keerthana.R", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC024' },
    { name: "Nikhil Sanjay S", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC025' },
    { name: "Rohith S.A", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC026' },
    { name: "Rosemitha.D", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC027' },
    { name: "Saindavi R", department: "BSC CS DA", year: "1", shift: "Shift 1", clubId: 'SRC24PC028' },
    { name: "Adikesavan", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC029' },
    { name: "CATHERIN KRISHA.F", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC030' },
    { name: "LAVANYA N", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC031' },
    { name: "RATHNESHKUMAR K", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC032' },
    { name: "Ritu R", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC033' },
    { name: "Riyaz", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC034' },
    { name: "S.Dharsini", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC035' },
    { name: "Anisha", department: "BSC CS AI DS", year: "1", shift: "Shift 2", clubId: 'SRC24PC036' },
    { name: "Ayyappadas. Tv", department: "BSC CT", year: "1", shift: "Shift 1", clubId: 'SRC24PC037' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC038' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC039' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC040' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC041' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC042' },
    { name: "Athiswara.P", department: "BSC CT", year: "1", shift: "Shift 2", clubId: 'SRC24PC043' },
    { name: "HASHISH LAA.H", department: "BSC CT", year: "1", shift: "Shift 2", clubId: 'SRC24PC044' },
    { name: "Jeevika.p", department: "BSC CT", year: "1", shift: "Shift 2", clubId: 'SRC24PC045' },
    { name: "SADASHINI V", department: "BSC CT", year: "1", shift: "Shift 2", clubId: 'SRC24PC046' },
    { name: "Shyam.A", department: "BSC CT", year: "1", shift: "Shift 2", clubId: 'SRC24PC047' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC048' },
    { name: "Deepsuthaarun R", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC049' },
    { name: "Karthikapriya", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC050' },
    { name: "Poornima", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC051' },
    { name: "Sree Nidhi R", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC052' },
    { name: "Srimathi G", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC053' },
    { name: "Yogesh CK", department: "BSC CYBER SECURITY", year: "1", shift: "Shift 2", clubId: 'SRC24PC054' },
    { name: "Levetha. S", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC055' },
    { name: "Nivarthana", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC056' },
    { name: "Santosh.M", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC057' },
    { name: "Sudharsan.S", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC058' },
    { name: "Tarun C.R", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC059' },
    { name: "Vaishnavi", department: "BSC FORENSIC SCIENCE", year: "1", shift: "Shift 2", clubId: 'SRC24PC060' },
    { name: "Hari Raj", department: "BSC CS CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC061' },
    { name: "Mohana krishnan R", department: "BSC CS CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC062' },
    { name: "Ragul D", department: "BSC CS CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC063' },
    { name: "Soniya", department: "BSC CS CS", year: "1", shift: "Shift 1", clubId: 'SRC24PC064' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC065' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC066' },
    { name: "DEVADHARSHINI J S", department: "BSC CS CS", year: "1", shift: "Shift 2", clubId: 'SRC24PC067' },
    { name: "HEMASRI.U", department: "BSC CS CS", year: "1", shift: "Shift 2", clubId: 'SRC24PC068' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC069' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC070' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC071' },
    { name: NaN, department: NaN, year: "1", shift: NaN, clubId: 'SRC24PC072' },
    { name: "Chandru s", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC073' },
    { name: "Chendur M", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC074' },
    { name: "Divya prabha M.N", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC075' },
    { name: "mithra", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC076' },
    { name: "Shuruthi sk", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC077' },
    { name: "Vignesh M", department: "BCA", year: "1", shift: "Shift 1", clubId: 'SRC24PC078' },
    { name: "Abishek", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC079' },
    { name: "Deepika Tamil Arasi.N.V", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC080' },
    { name: "Indra sree", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC081' },
    { name: "Jayasolomon k", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC082' },
    { name: "Vageesh.S.M", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC083' },
    { name: "Vaishnavi.G", department: "BCA", year: "1", shift: "Shift 2", clubId: 'SRC24PC084' },

];

export { TABLE_HEAD, TABLE_ROWS };
